name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
        env:
          FETCH_DEPTH: 1
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/actions/setup-gradle@v3.5.0
        with:
          gradle-version: 'wrapper'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        with:
          args: --ide,QDJVM, --fixes-strategy,apply
          pr-mode: 'false'
          push-fixes: 'pull-request'
          use-annotations: 'false'
          upload-result: 'true'
          use-caches: 'true'
          primary-cache-key: 'qodana-2024.3-${{ github.ref }}'
          additional-cache-key: 'qodana-2024.3'
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}